# Generated by Django 3.2.9 on 2021-11-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_head', models.CharField(max_length=200)),
                ('rec_descrip', models.TextField()),
                ('rec_1img', models.ImageField(null=True, upload_to='main/static/img/')),
                ('rec_2img', models.ImageField(null=True, upload_to='main/static/img/')),
                ('rec_composition', models.TextField()),
                ('rec_recipe', models.TextField()),
                ('rec_category', models.CharField(max_length=200)),
                ('rec_timecook', models.CharField(max_length=200)),
            ],
        ),
    ]
